/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChunkMetadata from './ChunkMetadata';

/**
 * The BatchQueuedChunkResponse model module.
 * @module model/BatchQueuedChunkResponse
 * @version 0.5.0
 */
class BatchQueuedChunkResponse {
    /**
     * Constructs a new <code>BatchQueuedChunkResponse</code>.
     * @alias module:model/BatchQueuedChunkResponse
     * @param chunkMetadata {Array.<module:model/ChunkMetadata>} 
     * @param posInQueue {Number} The current position the last access item is in the queue
     */
    constructor(chunkMetadata, posInQueue) { 
        
        BatchQueuedChunkResponse.initialize(this, chunkMetadata, posInQueue);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, chunkMetadata, posInQueue) { 
        obj['chunk_metadata'] = chunkMetadata;
        obj['pos_in_queue'] = posInQueue;
    }

    /**
     * Constructs a <code>BatchQueuedChunkResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BatchQueuedChunkResponse} obj Optional instance to populate.
     * @return {module:model/BatchQueuedChunkResponse} The populated <code>BatchQueuedChunkResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BatchQueuedChunkResponse();

            if (data.hasOwnProperty('chunk_metadata')) {
                obj['chunk_metadata'] = ApiClient.convertToType(data['chunk_metadata'], [ChunkMetadata]);
            }
            if (data.hasOwnProperty('pos_in_queue')) {
                obj['pos_in_queue'] = ApiClient.convertToType(data['pos_in_queue'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BatchQueuedChunkResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BatchQueuedChunkResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BatchQueuedChunkResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['chunk_metadata']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['chunk_metadata'])) {
                throw new Error("Expected the field `chunk_metadata` to be an array in the JSON data but got " + data['chunk_metadata']);
            }
            // validate the optional field `chunk_metadata` (array)
            for (const item of data['chunk_metadata']) {
                ChunkMetadata.validateJSON(item);
            };
        }

        return true;
    }


}

BatchQueuedChunkResponse.RequiredProperties = ["chunk_metadata", "pos_in_queue"];

/**
 * @member {Array.<module:model/ChunkMetadata>} chunk_metadata
 */
BatchQueuedChunkResponse.prototype['chunk_metadata'] = undefined;

/**
 * The current position the last access item is in the queue
 * @member {Number} pos_in_queue
 */
BatchQueuedChunkResponse.prototype['pos_in_queue'] = undefined;






export default BatchQueuedChunkResponse;

