/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChunkGroup from './ChunkGroup';
import ChunkMetadataWithFileData from './ChunkMetadataWithFileData';

/**
 * The BookmarkData model module.
 * @module model/BookmarkData
 * @version 0.5.0
 */
class BookmarkData {
    /**
     * Constructs a new <code>BookmarkData</code>.
     * @alias module:model/BookmarkData
     * @param chunks {Array.<module:model/ChunkMetadataWithFileData>} 
     * @param group {module:model/ChunkGroup} 
     * @param totalPages {Number} 
     */
    constructor(chunks, group, totalPages) { 
        
        BookmarkData.initialize(this, chunks, group, totalPages);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, chunks, group, totalPages) { 
        obj['chunks'] = chunks;
        obj['group'] = group;
        obj['total_pages'] = totalPages;
    }

    /**
     * Constructs a <code>BookmarkData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BookmarkData} obj Optional instance to populate.
     * @return {module:model/BookmarkData} The populated <code>BookmarkData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BookmarkData();

            if (data.hasOwnProperty('chunks')) {
                obj['chunks'] = ApiClient.convertToType(data['chunks'], [ChunkMetadataWithFileData]);
            }
            if (data.hasOwnProperty('group')) {
                obj['group'] = ChunkGroup.constructFromObject(data['group']);
            }
            if (data.hasOwnProperty('total_pages')) {
                obj['total_pages'] = ApiClient.convertToType(data['total_pages'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BookmarkData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BookmarkData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BookmarkData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['chunks']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['chunks'])) {
                throw new Error("Expected the field `chunks` to be an array in the JSON data but got " + data['chunks']);
            }
            // validate the optional field `chunks` (array)
            for (const item of data['chunks']) {
                ChunkMetadataWithFileData.validateJSON(item);
            };
        }
        // validate the optional field `group`
        if (data['group']) { // data not null
          ChunkGroup.validateJSON(data['group']);
        }

        return true;
    }


}

BookmarkData.RequiredProperties = ["chunks", "group", "total_pages"];

/**
 * @member {Array.<module:model/ChunkMetadataWithFileData>} chunks
 */
BookmarkData.prototype['chunks'] = undefined;

/**
 * @member {module:model/ChunkGroup} group
 */
BookmarkData.prototype['group'] = undefined;

/**
 * @member {Number} total_pages
 */
BookmarkData.prototype['total_pages'] = undefined;






export default BookmarkData;

