/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SlimGroup from './SlimGroup';

/**
 * The BookmarkGroupResult model module.
 * @module model/BookmarkGroupResult
 * @version 0.5.0
 */
class BookmarkGroupResult {
    /**
     * Constructs a new <code>BookmarkGroupResult</code>.
     * @alias module:model/BookmarkGroupResult
     * @param chunkUuid {String} 
     * @param slimGroups {Array.<module:model/SlimGroup>} 
     */
    constructor(chunkUuid, slimGroups) { 
        
        BookmarkGroupResult.initialize(this, chunkUuid, slimGroups);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, chunkUuid, slimGroups) { 
        obj['chunk_uuid'] = chunkUuid;
        obj['slim_groups'] = slimGroups;
    }

    /**
     * Constructs a <code>BookmarkGroupResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BookmarkGroupResult} obj Optional instance to populate.
     * @return {module:model/BookmarkGroupResult} The populated <code>BookmarkGroupResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BookmarkGroupResult();

            if (data.hasOwnProperty('chunk_uuid')) {
                obj['chunk_uuid'] = ApiClient.convertToType(data['chunk_uuid'], 'String');
            }
            if (data.hasOwnProperty('slim_groups')) {
                obj['slim_groups'] = ApiClient.convertToType(data['slim_groups'], [SlimGroup]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BookmarkGroupResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BookmarkGroupResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BookmarkGroupResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['chunk_uuid'] && !(typeof data['chunk_uuid'] === 'string' || data['chunk_uuid'] instanceof String)) {
            throw new Error("Expected the field `chunk_uuid` to be a primitive type in the JSON string but got " + data['chunk_uuid']);
        }
        if (data['slim_groups']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['slim_groups'])) {
                throw new Error("Expected the field `slim_groups` to be an array in the JSON data but got " + data['slim_groups']);
            }
            // validate the optional field `slim_groups` (array)
            for (const item of data['slim_groups']) {
                SlimGroup.validateJSON(item);
            };
        }

        return true;
    }


}

BookmarkGroupResult.RequiredProperties = ["chunk_uuid", "slim_groups"];

/**
 * @member {String} chunk_uuid
 */
BookmarkGroupResult.prototype['chunk_uuid'] = undefined;

/**
 * @member {Array.<module:model/SlimGroup>} slim_groups
 */
BookmarkGroupResult.prototype['slim_groups'] = undefined;






export default BookmarkGroupResult;

