/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChunkData model module.
 * @module model/ChunkData
 * @version 0.5.0
 */
class ChunkData {
    /**
     * Constructs a new <code>ChunkData</code>.
     * @alias module:model/ChunkData
     */
    constructor() { 
        
        ChunkData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChunkData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChunkData} obj Optional instance to populate.
     * @return {module:model/ChunkData} The populated <code>ChunkData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChunkData();

            if (data.hasOwnProperty('chunk_html')) {
                obj['chunk_html'] = ApiClient.convertToType(data['chunk_html'], 'String');
            }
            if (data.hasOwnProperty('chunk_vector')) {
                obj['chunk_vector'] = ApiClient.convertToType(data['chunk_vector'], ['Number']);
            }
            if (data.hasOwnProperty('file_id')) {
                obj['file_id'] = ApiClient.convertToType(data['file_id'], 'String');
            }
            if (data.hasOwnProperty('group_ids')) {
                obj['group_ids'] = ApiClient.convertToType(data['group_ids'], ['String']);
            }
            if (data.hasOwnProperty('group_tracking_ids')) {
                obj['group_tracking_ids'] = ApiClient.convertToType(data['group_tracking_ids'], ['String']);
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('split_avg')) {
                obj['split_avg'] = ApiClient.convertToType(data['split_avg'], 'Boolean');
            }
            if (data.hasOwnProperty('tag_set')) {
                obj['tag_set'] = ApiClient.convertToType(data['tag_set'], ['String']);
            }
            if (data.hasOwnProperty('time_stamp')) {
                obj['time_stamp'] = ApiClient.convertToType(data['time_stamp'], 'String');
            }
            if (data.hasOwnProperty('tracking_id')) {
                obj['tracking_id'] = ApiClient.convertToType(data['tracking_id'], 'String');
            }
            if (data.hasOwnProperty('upsert_by_tracking_id')) {
                obj['upsert_by_tracking_id'] = ApiClient.convertToType(data['upsert_by_tracking_id'], 'Boolean');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChunkData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChunkData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['chunk_html'] && !(typeof data['chunk_html'] === 'string' || data['chunk_html'] instanceof String)) {
            throw new Error("Expected the field `chunk_html` to be a primitive type in the JSON string but got " + data['chunk_html']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['chunk_vector'])) {
            throw new Error("Expected the field `chunk_vector` to be an array in the JSON data but got " + data['chunk_vector']);
        }
        // ensure the json data is a string
        if (data['file_id'] && !(typeof data['file_id'] === 'string' || data['file_id'] instanceof String)) {
            throw new Error("Expected the field `file_id` to be a primitive type in the JSON string but got " + data['file_id']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['group_ids'])) {
            throw new Error("Expected the field `group_ids` to be an array in the JSON data but got " + data['group_ids']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['group_tracking_ids'])) {
            throw new Error("Expected the field `group_tracking_ids` to be an array in the JSON data but got " + data['group_tracking_ids']);
        }
        // ensure the json data is a string
        if (data['link'] && !(typeof data['link'] === 'string' || data['link'] instanceof String)) {
            throw new Error("Expected the field `link` to be a primitive type in the JSON string but got " + data['link']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tag_set'])) {
            throw new Error("Expected the field `tag_set` to be an array in the JSON data but got " + data['tag_set']);
        }
        // ensure the json data is a string
        if (data['time_stamp'] && !(typeof data['time_stamp'] === 'string' || data['time_stamp'] instanceof String)) {
            throw new Error("Expected the field `time_stamp` to be a primitive type in the JSON string but got " + data['time_stamp']);
        }
        // ensure the json data is a string
        if (data['tracking_id'] && !(typeof data['tracking_id'] === 'string' || data['tracking_id'] instanceof String)) {
            throw new Error("Expected the field `tracking_id` to be a primitive type in the JSON string but got " + data['tracking_id']);
        }

        return true;
    }


}



/**
 * HTML content of the chunk. This can also be plaintext. The innerText of the HTML will be used to create the embedding vector. The point of using HTML is for convienience, as some users have applications where users submit HTML content.
 * @member {String} chunk_html
 */
ChunkData.prototype['chunk_html'] = undefined;

/**
 * Chunk_vector is a vector of floats which can be used instead of generating a new embedding. This is useful for when you are using a pre-embedded dataset. If this is not provided, the innerText of the chunk_html will be used to create the embedding.
 * @member {Array.<Number>} chunk_vector
 */
ChunkData.prototype['chunk_vector'] = undefined;

/**
 * File_uuid is the uuid of the file that the chunk is associated with. This is used to associate chunks with files. This is useful for when you want to delete a file and all of its associated chunks.
 * @member {String} file_id
 */
ChunkData.prototype['file_id'] = undefined;

/**
 * Group ids are the ids of the groups that the chunk should be placed into. This is useful for when you want to create a chunk and add it to a group or multiple groups in one request. Necessary because this route queues the chunk for ingestion and the chunk may not exist yet immediately after response.
 * @member {Array.<String>} group_ids
 */
ChunkData.prototype['group_ids'] = undefined;

/**
 * Group tracking_ids are the tracking_ids of the groups that the chunk should be placed into. This is useful for when you want to create a chunk and add it to a group or multiple groups in one request. Necessary because this route queues the chunk for ingestion and the chunk may not exist yet immediately after response.
 * @member {Array.<String>} group_tracking_ids
 */
ChunkData.prototype['group_tracking_ids'] = undefined;

/**
 * Link to the chunk. This can also be any string. Frequently, this is a link to the source of the chunk. The link value will not affect the embedding creation.
 * @member {String} link
 */
ChunkData.prototype['link'] = undefined;

/**
 * Metadata is a JSON object which can be used to filter chunks. This is useful for when you want to filter chunks by arbitrary metadata. Unlike with tag filtering, there is a performance hit for filtering on metadata.
 * @member {Object} metadata
 */
ChunkData.prototype['metadata'] = undefined;

/**
 * Split avg is a boolean which tells the server to split the text in the chunk_html into smaller chunks and average their resulting vectors. This is useful for when you want to create a chunk from a large piece of text and want to split it into smaller chunks to create a more fuzzy average dense vector. The sparse vector will be generated normally with no averaging. By default this is false.
 * @member {Boolean} split_avg
 */
ChunkData.prototype['split_avg'] = undefined;

/**
 * Tag set is a list of tags. This can be used to filter chunks by tag. Unlike with metadata filtering, HNSW indices will exist for each tag such that there is not a performance hit for filtering on them.
 * @member {Array.<String>} tag_set
 */
ChunkData.prototype['tag_set'] = undefined;

/**
 * Time_stamp should be an ISO 8601 combined date and time without timezone. It is used for time window filtering and recency-biasing search results.
 * @member {String} time_stamp
 */
ChunkData.prototype['time_stamp'] = undefined;

/**
 * Tracking_id is a string which can be used to identify a chunk. This is useful for when you are coordinating with an external system and want to use the tracking_id to identify the chunk.
 * @member {String} tracking_id
 */
ChunkData.prototype['tracking_id'] = undefined;

/**
 * Upsert when a chunk with the same tracking_id exists. By default this is false, and the request will fail if a chunk with the same tracking_id exists. If this is true, the chunk will be updated if a chunk with the same tracking_id exists.
 * @member {Boolean} upsert_by_tracking_id
 */
ChunkData.prototype['upsert_by_tracking_id'] = undefined;

/**
 * Weight is a float which can be used to bias search results. This is useful for when you want to bias search results for a chunk. The magnitude only matters relative to other chunks in the chunk's dataset dataset.
 * @member {Number} weight
 */
ChunkData.prototype['weight'] = undefined;






export default ChunkData;

