/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ClientDatasetConfiguration model module.
 * @module model/ClientDatasetConfiguration
 * @version 0.5.0
 */
class ClientDatasetConfiguration {
    /**
     * Constructs a new <code>ClientDatasetConfiguration</code>.
     * @alias module:model/ClientDatasetConfiguration
     * @param FILE_NAME_KEY {String} 
     */
    constructor(FILE_NAME_KEY) { 
        
        ClientDatasetConfiguration.initialize(this, FILE_NAME_KEY);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, FILE_NAME_KEY) { 
        obj['FILE_NAME_KEY'] = FILE_NAME_KEY;
    }

    /**
     * Constructs a <code>ClientDatasetConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClientDatasetConfiguration} obj Optional instance to populate.
     * @return {module:model/ClientDatasetConfiguration} The populated <code>ClientDatasetConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClientDatasetConfiguration();

            if (data.hasOwnProperty('CREATE_CHUNK_FEATURE')) {
                obj['CREATE_CHUNK_FEATURE'] = ApiClient.convertToType(data['CREATE_CHUNK_FEATURE'], 'Boolean');
            }
            if (data.hasOwnProperty('DATE_RANGE_VALUE')) {
                obj['DATE_RANGE_VALUE'] = ApiClient.convertToType(data['DATE_RANGE_VALUE'], 'String');
            }
            if (data.hasOwnProperty('DOCUMENT_UPLOAD_FEATURE')) {
                obj['DOCUMENT_UPLOAD_FEATURE'] = ApiClient.convertToType(data['DOCUMENT_UPLOAD_FEATURE'], 'Boolean');
            }
            if (data.hasOwnProperty('FILE_NAME_KEY')) {
                obj['FILE_NAME_KEY'] = ApiClient.convertToType(data['FILE_NAME_KEY'], 'String');
            }
            if (data.hasOwnProperty('FILTER_ITEMS')) {
                obj['FILTER_ITEMS'] = ApiClient.convertToType(data['FILTER_ITEMS'], Object);
            }
            if (data.hasOwnProperty('FRONTMATTER_VALS')) {
                obj['FRONTMATTER_VALS'] = ApiClient.convertToType(data['FRONTMATTER_VALS'], 'String');
            }
            if (data.hasOwnProperty('IMAGE_RANGE_END_KEY')) {
                obj['IMAGE_RANGE_END_KEY'] = ApiClient.convertToType(data['IMAGE_RANGE_END_KEY'], 'String');
            }
            if (data.hasOwnProperty('IMAGE_RANGE_START_KEY')) {
                obj['IMAGE_RANGE_START_KEY'] = ApiClient.convertToType(data['IMAGE_RANGE_START_KEY'], 'String');
            }
            if (data.hasOwnProperty('LINES_BEFORE_SHOW_MORE')) {
                obj['LINES_BEFORE_SHOW_MORE'] = ApiClient.convertToType(data['LINES_BEFORE_SHOW_MORE'], 'Number');
            }
            if (data.hasOwnProperty('SEARCH_QUERIES')) {
                obj['SEARCH_QUERIES'] = ApiClient.convertToType(data['SEARCH_QUERIES'], 'String');
            }
            if (data.hasOwnProperty('SUGGESTED_QUERIES')) {
                obj['SUGGESTED_QUERIES'] = ApiClient.convertToType(data['SUGGESTED_QUERIES'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ClientDatasetConfiguration</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ClientDatasetConfiguration</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ClientDatasetConfiguration.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['DATE_RANGE_VALUE'] && !(typeof data['DATE_RANGE_VALUE'] === 'string' || data['DATE_RANGE_VALUE'] instanceof String)) {
            throw new Error("Expected the field `DATE_RANGE_VALUE` to be a primitive type in the JSON string but got " + data['DATE_RANGE_VALUE']);
        }
        // ensure the json data is a string
        if (data['FILE_NAME_KEY'] && !(typeof data['FILE_NAME_KEY'] === 'string' || data['FILE_NAME_KEY'] instanceof String)) {
            throw new Error("Expected the field `FILE_NAME_KEY` to be a primitive type in the JSON string but got " + data['FILE_NAME_KEY']);
        }
        // ensure the json data is a string
        if (data['FRONTMATTER_VALS'] && !(typeof data['FRONTMATTER_VALS'] === 'string' || data['FRONTMATTER_VALS'] instanceof String)) {
            throw new Error("Expected the field `FRONTMATTER_VALS` to be a primitive type in the JSON string but got " + data['FRONTMATTER_VALS']);
        }
        // ensure the json data is a string
        if (data['IMAGE_RANGE_END_KEY'] && !(typeof data['IMAGE_RANGE_END_KEY'] === 'string' || data['IMAGE_RANGE_END_KEY'] instanceof String)) {
            throw new Error("Expected the field `IMAGE_RANGE_END_KEY` to be a primitive type in the JSON string but got " + data['IMAGE_RANGE_END_KEY']);
        }
        // ensure the json data is a string
        if (data['IMAGE_RANGE_START_KEY'] && !(typeof data['IMAGE_RANGE_START_KEY'] === 'string' || data['IMAGE_RANGE_START_KEY'] instanceof String)) {
            throw new Error("Expected the field `IMAGE_RANGE_START_KEY` to be a primitive type in the JSON string but got " + data['IMAGE_RANGE_START_KEY']);
        }
        // ensure the json data is a string
        if (data['SEARCH_QUERIES'] && !(typeof data['SEARCH_QUERIES'] === 'string' || data['SEARCH_QUERIES'] instanceof String)) {
            throw new Error("Expected the field `SEARCH_QUERIES` to be a primitive type in the JSON string but got " + data['SEARCH_QUERIES']);
        }
        // ensure the json data is a string
        if (data['SUGGESTED_QUERIES'] && !(typeof data['SUGGESTED_QUERIES'] === 'string' || data['SUGGESTED_QUERIES'] instanceof String)) {
            throw new Error("Expected the field `SUGGESTED_QUERIES` to be a primitive type in the JSON string but got " + data['SUGGESTED_QUERIES']);
        }

        return true;
    }


}

ClientDatasetConfiguration.RequiredProperties = ["FILE_NAME_KEY"];

/**
 * @member {Boolean} CREATE_CHUNK_FEATURE
 */
ClientDatasetConfiguration.prototype['CREATE_CHUNK_FEATURE'] = undefined;

/**
 * @member {String} DATE_RANGE_VALUE
 */
ClientDatasetConfiguration.prototype['DATE_RANGE_VALUE'] = undefined;

/**
 * @member {Boolean} DOCUMENT_UPLOAD_FEATURE
 */
ClientDatasetConfiguration.prototype['DOCUMENT_UPLOAD_FEATURE'] = undefined;

/**
 * @member {String} FILE_NAME_KEY
 */
ClientDatasetConfiguration.prototype['FILE_NAME_KEY'] = undefined;

/**
 * @member {Object} FILTER_ITEMS
 */
ClientDatasetConfiguration.prototype['FILTER_ITEMS'] = undefined;

/**
 * @member {String} FRONTMATTER_VALS
 */
ClientDatasetConfiguration.prototype['FRONTMATTER_VALS'] = undefined;

/**
 * @member {String} IMAGE_RANGE_END_KEY
 */
ClientDatasetConfiguration.prototype['IMAGE_RANGE_END_KEY'] = undefined;

/**
 * @member {String} IMAGE_RANGE_START_KEY
 */
ClientDatasetConfiguration.prototype['IMAGE_RANGE_START_KEY'] = undefined;

/**
 * @member {Number} LINES_BEFORE_SHOW_MORE
 */
ClientDatasetConfiguration.prototype['LINES_BEFORE_SHOW_MORE'] = undefined;

/**
 * @member {String} SEARCH_QUERIES
 */
ClientDatasetConfiguration.prototype['SEARCH_QUERIES'] = undefined;

/**
 * @member {String} SUGGESTED_QUERIES
 */
ClientDatasetConfiguration.prototype['SUGGESTED_QUERIES'] = undefined;






export default ClientDatasetConfiguration;

