/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteDatasetRequest model module.
 * @module model/DeleteDatasetRequest
 * @version 0.5.0
 */
class DeleteDatasetRequest {
    /**
     * Constructs a new <code>DeleteDatasetRequest</code>.
     * @alias module:model/DeleteDatasetRequest
     * @param datasetId {String} The id of the dataset you want to delete.
     */
    constructor(datasetId) { 
        
        DeleteDatasetRequest.initialize(this, datasetId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, datasetId) { 
        obj['dataset_id'] = datasetId;
    }

    /**
     * Constructs a <code>DeleteDatasetRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteDatasetRequest} obj Optional instance to populate.
     * @return {module:model/DeleteDatasetRequest} The populated <code>DeleteDatasetRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteDatasetRequest();

            if (data.hasOwnProperty('dataset_id')) {
                obj['dataset_id'] = ApiClient.convertToType(data['dataset_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteDatasetRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteDatasetRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeleteDatasetRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['dataset_id'] && !(typeof data['dataset_id'] === 'string' || data['dataset_id'] instanceof String)) {
            throw new Error("Expected the field `dataset_id` to be a primitive type in the JSON string but got " + data['dataset_id']);
        }

        return true;
    }


}

DeleteDatasetRequest.RequiredProperties = ["dataset_id"];

/**
 * The id of the dataset you want to delete.
 * @member {String} dataset_id
 */
DeleteDatasetRequest.prototype['dataset_id'] = undefined;






export default DeleteDatasetRequest;

