/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Event from './Event';

/**
 * The EventReturn model module.
 * @module model/EventReturn
 * @version 0.5.0
 */
class EventReturn {
    /**
     * Constructs a new <code>EventReturn</code>.
     * @alias module:model/EventReturn
     * @param events {Array.<module:model/Event>} 
     * @param pageCount {Number} 
     */
    constructor(events, pageCount) { 
        
        EventReturn.initialize(this, events, pageCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, events, pageCount) { 
        obj['events'] = events;
        obj['page_count'] = pageCount;
    }

    /**
     * Constructs a <code>EventReturn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventReturn} obj Optional instance to populate.
     * @return {module:model/EventReturn} The populated <code>EventReturn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventReturn();

            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [Event]);
            }
            if (data.hasOwnProperty('page_count')) {
                obj['page_count'] = ApiClient.convertToType(data['page_count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventReturn</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventReturn</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventReturn.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['events']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['events'])) {
                throw new Error("Expected the field `events` to be an array in the JSON data but got " + data['events']);
            }
            // validate the optional field `events` (array)
            for (const item of data['events']) {
                Event.validateJSON(item);
            };
        }

        return true;
    }


}

EventReturn.RequiredProperties = ["events", "page_count"];

/**
 * @member {Array.<module:model/Event>} events
 */
EventReturn.prototype['events'] = undefined;

/**
 * @member {Number} page_count
 */
EventReturn.prototype['page_count'] = undefined;






export default EventReturn;

