/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The File model module.
 * @module model/File
 * @version 0.5.0
 */
class File {
    /**
     * Constructs a new <code>File</code>.
     * @alias module:model/File
     * @param createdAt {Date} 
     * @param datasetId {String} 
     * @param fileName {String} 
     * @param id {String} 
     * @param size {Number} 
     * @param updatedAt {Date} 
     */
    constructor(createdAt, datasetId, fileName, id, size, updatedAt) { 
        
        File.initialize(this, createdAt, datasetId, fileName, id, size, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, createdAt, datasetId, fileName, id, size, updatedAt) { 
        obj['created_at'] = createdAt;
        obj['dataset_id'] = datasetId;
        obj['file_name'] = fileName;
        obj['id'] = id;
        obj['size'] = size;
        obj['updated_at'] = updatedAt;
    }

    /**
     * Constructs a <code>File</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/File} obj Optional instance to populate.
     * @return {module:model/File} The populated <code>File</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new File();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('dataset_id')) {
                obj['dataset_id'] = ApiClient.convertToType(data['dataset_id'], 'String');
            }
            if (data.hasOwnProperty('file_name')) {
                obj['file_name'] = ApiClient.convertToType(data['file_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('tag_set')) {
                obj['tag_set'] = ApiClient.convertToType(data['tag_set'], 'String');
            }
            if (data.hasOwnProperty('time_stamp')) {
                obj['time_stamp'] = ApiClient.convertToType(data['time_stamp'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>File</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>File</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of File.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['dataset_id'] && !(typeof data['dataset_id'] === 'string' || data['dataset_id'] instanceof String)) {
            throw new Error("Expected the field `dataset_id` to be a primitive type in the JSON string but got " + data['dataset_id']);
        }
        // ensure the json data is a string
        if (data['file_name'] && !(typeof data['file_name'] === 'string' || data['file_name'] instanceof String)) {
            throw new Error("Expected the field `file_name` to be a primitive type in the JSON string but got " + data['file_name']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['link'] && !(typeof data['link'] === 'string' || data['link'] instanceof String)) {
            throw new Error("Expected the field `link` to be a primitive type in the JSON string but got " + data['link']);
        }
        // ensure the json data is a string
        if (data['tag_set'] && !(typeof data['tag_set'] === 'string' || data['tag_set'] instanceof String)) {
            throw new Error("Expected the field `tag_set` to be a primitive type in the JSON string but got " + data['tag_set']);
        }

        return true;
    }


}

File.RequiredProperties = ["created_at", "dataset_id", "file_name", "id", "size", "updated_at"];

/**
 * @member {Date} created_at
 */
File.prototype['created_at'] = undefined;

/**
 * @member {String} dataset_id
 */
File.prototype['dataset_id'] = undefined;

/**
 * @member {String} file_name
 */
File.prototype['file_name'] = undefined;

/**
 * @member {String} id
 */
File.prototype['id'] = undefined;

/**
 * @member {String} link
 */
File.prototype['link'] = undefined;

/**
 * @member {Object} metadata
 */
File.prototype['metadata'] = undefined;

/**
 * @member {Number} size
 */
File.prototype['size'] = undefined;

/**
 * @member {String} tag_set
 */
File.prototype['tag_set'] = undefined;

/**
 * @member {Date} time_stamp
 */
File.prototype['time_stamp'] = undefined;

/**
 * @member {Date} updated_at
 */
File.prototype['updated_at'] = undefined;






export default File;

