/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetGroupsForChunksData model module.
 * @module model/GetGroupsForChunksData
 * @version 0.5.0
 */
class GetGroupsForChunksData {
    /**
     * Constructs a new <code>GetGroupsForChunksData</code>.
     * @alias module:model/GetGroupsForChunksData
     * @param chunkIds {Array.<String>} 
     */
    constructor(chunkIds) { 
        
        GetGroupsForChunksData.initialize(this, chunkIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, chunkIds) { 
        obj['chunk_ids'] = chunkIds;
    }

    /**
     * Constructs a <code>GetGroupsForChunksData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetGroupsForChunksData} obj Optional instance to populate.
     * @return {module:model/GetGroupsForChunksData} The populated <code>GetGroupsForChunksData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetGroupsForChunksData();

            if (data.hasOwnProperty('chunk_ids')) {
                obj['chunk_ids'] = ApiClient.convertToType(data['chunk_ids'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetGroupsForChunksData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetGroupsForChunksData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetGroupsForChunksData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['chunk_ids'])) {
            throw new Error("Expected the field `chunk_ids` to be an array in the JSON data but got " + data['chunk_ids']);
        }

        return true;
    }


}

GetGroupsForChunksData.RequiredProperties = ["chunk_ids"];

/**
 * @member {Array.<String>} chunk_ids
 */
GetGroupsForChunksData.prototype['chunk_ids'] = undefined;






export default GetGroupsForChunksData;

