/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Message model module.
 * @module model/Message
 * @version 0.5.0
 */
class Message {
    /**
     * Constructs a new <code>Message</code>.
     * @alias module:model/Message
     * @param content {String} 
     * @param createdAt {Date} 
     * @param datasetId {String} 
     * @param deleted {Boolean} 
     * @param id {String} 
     * @param role {String} 
     * @param sortOrder {Number} 
     * @param topicId {String} 
     * @param updatedAt {Date} 
     */
    constructor(content, createdAt, datasetId, deleted, id, role, sortOrder, topicId, updatedAt) { 
        
        Message.initialize(this, content, createdAt, datasetId, deleted, id, role, sortOrder, topicId, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content, createdAt, datasetId, deleted, id, role, sortOrder, topicId, updatedAt) { 
        obj['content'] = content;
        obj['created_at'] = createdAt;
        obj['dataset_id'] = datasetId;
        obj['deleted'] = deleted;
        obj['id'] = id;
        obj['role'] = role;
        obj['sort_order'] = sortOrder;
        obj['topic_id'] = topicId;
        obj['updated_at'] = updatedAt;
    }

    /**
     * Constructs a <code>Message</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Message} obj Optional instance to populate.
     * @return {module:model/Message} The populated <code>Message</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Message();

            if (data.hasOwnProperty('completion_tokens')) {
                obj['completion_tokens'] = ApiClient.convertToType(data['completion_tokens'], 'Number');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('dataset_id')) {
                obj['dataset_id'] = ApiClient.convertToType(data['dataset_id'], 'String');
            }
            if (data.hasOwnProperty('deleted')) {
                obj['deleted'] = ApiClient.convertToType(data['deleted'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('prompt_tokens')) {
                obj['prompt_tokens'] = ApiClient.convertToType(data['prompt_tokens'], 'Number');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('sort_order')) {
                obj['sort_order'] = ApiClient.convertToType(data['sort_order'], 'Number');
            }
            if (data.hasOwnProperty('topic_id')) {
                obj['topic_id'] = ApiClient.convertToType(data['topic_id'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Message</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Message</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Message.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is a string
        if (data['dataset_id'] && !(typeof data['dataset_id'] === 'string' || data['dataset_id'] instanceof String)) {
            throw new Error("Expected the field `dataset_id` to be a primitive type in the JSON string but got " + data['dataset_id']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['topic_id'] && !(typeof data['topic_id'] === 'string' || data['topic_id'] instanceof String)) {
            throw new Error("Expected the field `topic_id` to be a primitive type in the JSON string but got " + data['topic_id']);
        }

        return true;
    }


}

Message.RequiredProperties = ["content", "created_at", "dataset_id", "deleted", "id", "role", "sort_order", "topic_id", "updated_at"];

/**
 * @member {Number} completion_tokens
 */
Message.prototype['completion_tokens'] = undefined;

/**
 * @member {String} content
 */
Message.prototype['content'] = undefined;

/**
 * @member {Date} created_at
 */
Message.prototype['created_at'] = undefined;

/**
 * @member {String} dataset_id
 */
Message.prototype['dataset_id'] = undefined;

/**
 * @member {Boolean} deleted
 */
Message.prototype['deleted'] = undefined;

/**
 * @member {String} id
 */
Message.prototype['id'] = undefined;

/**
 * @member {Number} prompt_tokens
 */
Message.prototype['prompt_tokens'] = undefined;

/**
 * @member {String} role
 */
Message.prototype['role'] = undefined;

/**
 * @member {Number} sort_order
 */
Message.prototype['sort_order'] = undefined;

/**
 * @member {String} topic_id
 */
Message.prototype['topic_id'] = undefined;

/**
 * @member {Date} updated_at
 */
Message.prototype['updated_at'] = undefined;






export default Message;

