/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChunkFilter from './ChunkFilter';

/**
 * The ReccomendGroupChunksRequest model module.
 * @module model/ReccomendGroupChunksRequest
 * @version 0.5.0
 */
class ReccomendGroupChunksRequest {
    /**
     * Constructs a new <code>ReccomendGroupChunksRequest</code>.
     * @alias module:model/ReccomendGroupChunksRequest
     */
    constructor() { 
        
        ReccomendGroupChunksRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReccomendGroupChunksRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReccomendGroupChunksRequest} obj Optional instance to populate.
     * @return {module:model/ReccomendGroupChunksRequest} The populated <code>ReccomendGroupChunksRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReccomendGroupChunksRequest();

            if (data.hasOwnProperty('filters')) {
                obj['filters'] = ApiClient.convertToType(data['filters'], ChunkFilter);
            }
            if (data.hasOwnProperty('group_size')) {
                obj['group_size'] = ApiClient.convertToType(data['group_size'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('negative_group_ids')) {
                obj['negative_group_ids'] = ApiClient.convertToType(data['negative_group_ids'], ['String']);
            }
            if (data.hasOwnProperty('negative_group_tracking_ids')) {
                obj['negative_group_tracking_ids'] = ApiClient.convertToType(data['negative_group_tracking_ids'], ['String']);
            }
            if (data.hasOwnProperty('positive_group_ids')) {
                obj['positive_group_ids'] = ApiClient.convertToType(data['positive_group_ids'], ['String']);
            }
            if (data.hasOwnProperty('positive_group_tracking_ids')) {
                obj['positive_group_tracking_ids'] = ApiClient.convertToType(data['positive_group_tracking_ids'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReccomendGroupChunksRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReccomendGroupChunksRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `filters`
        if (data['filters']) { // data not null
          ChunkFilter.validateJSON(data['filters']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['negative_group_ids'])) {
            throw new Error("Expected the field `negative_group_ids` to be an array in the JSON data but got " + data['negative_group_ids']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['negative_group_tracking_ids'])) {
            throw new Error("Expected the field `negative_group_tracking_ids` to be an array in the JSON data but got " + data['negative_group_tracking_ids']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['positive_group_ids'])) {
            throw new Error("Expected the field `positive_group_ids` to be an array in the JSON data but got " + data['positive_group_ids']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['positive_group_tracking_ids'])) {
            throw new Error("Expected the field `positive_group_tracking_ids` to be an array in the JSON data but got " + data['positive_group_tracking_ids']);
        }

        return true;
    }


}



/**
 * @member {module:model/ChunkFilter} filters
 */
ReccomendGroupChunksRequest.prototype['filters'] = undefined;

/**
 * The number of chunks to fetch for each group. This is the number of chunks which will be returned in the response for each group. The default is 10.
 * @member {Number} group_size
 */
ReccomendGroupChunksRequest.prototype['group_size'] = undefined;

/**
 * The number of groups to return. This is the number of groups which will be returned in the response. The default is 10.
 * @member {Number} limit
 */
ReccomendGroupChunksRequest.prototype['limit'] = undefined;

/**
 * The  ids of the groups to be used as negative examples for the recommendation. The groups in this array will be used to filter out similar groups.
 * @member {Array.<String>} negative_group_ids
 */
ReccomendGroupChunksRequest.prototype['negative_group_ids'] = undefined;

/**
 * The  ids of the groups to be used as negative examples for the recommendation. The groups in this array will be used to filter out similar groups.
 * @member {Array.<String>} negative_group_tracking_ids
 */
ReccomendGroupChunksRequest.prototype['negative_group_tracking_ids'] = undefined;

/**
 * The  ids of the groups to be used as positive examples for the recommendation. The groups in this array will be used to find similar groups.
 * @member {Array.<String>} positive_group_ids
 */
ReccomendGroupChunksRequest.prototype['positive_group_ids'] = undefined;

/**
 * The  ids of the groups to be used as positive examples for the recommendation. The groups in this array will be used to find similar groups.
 * @member {Array.<String>} positive_group_tracking_ids
 */
ReccomendGroupChunksRequest.prototype['positive_group_tracking_ids'] = undefined;






export default ReccomendGroupChunksRequest;

