/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScoreChunkDTO from './ScoreChunkDTO';

/**
 * The SearchChunkQueryResponseBody model module.
 * @module model/SearchChunkQueryResponseBody
 * @version 0.5.0
 */
class SearchChunkQueryResponseBody {
    /**
     * Constructs a new <code>SearchChunkQueryResponseBody</code>.
     * @alias module:model/SearchChunkQueryResponseBody
     * @param scoreChunks {Array.<module:model/ScoreChunkDTO>} 
     * @param totalChunkPages {Number} 
     */
    constructor(scoreChunks, totalChunkPages) { 
        
        SearchChunkQueryResponseBody.initialize(this, scoreChunks, totalChunkPages);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, scoreChunks, totalChunkPages) { 
        obj['score_chunks'] = scoreChunks;
        obj['total_chunk_pages'] = totalChunkPages;
    }

    /**
     * Constructs a <code>SearchChunkQueryResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchChunkQueryResponseBody} obj Optional instance to populate.
     * @return {module:model/SearchChunkQueryResponseBody} The populated <code>SearchChunkQueryResponseBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchChunkQueryResponseBody();

            if (data.hasOwnProperty('score_chunks')) {
                obj['score_chunks'] = ApiClient.convertToType(data['score_chunks'], [ScoreChunkDTO]);
            }
            if (data.hasOwnProperty('total_chunk_pages')) {
                obj['total_chunk_pages'] = ApiClient.convertToType(data['total_chunk_pages'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchChunkQueryResponseBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchChunkQueryResponseBody</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SearchChunkQueryResponseBody.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['score_chunks']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['score_chunks'])) {
                throw new Error("Expected the field `score_chunks` to be an array in the JSON data but got " + data['score_chunks']);
            }
            // validate the optional field `score_chunks` (array)
            for (const item of data['score_chunks']) {
                ScoreChunkDTO.validateJSON(item);
            };
        }

        return true;
    }


}

SearchChunkQueryResponseBody.RequiredProperties = ["score_chunks", "total_chunk_pages"];

/**
 * @member {Array.<module:model/ScoreChunkDTO>} score_chunks
 */
SearchChunkQueryResponseBody.prototype['score_chunks'] = undefined;

/**
 * @member {Number} total_chunk_pages
 */
SearchChunkQueryResponseBody.prototype['total_chunk_pages'] = undefined;






export default SearchChunkQueryResponseBody;

