/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GroupScoreChunkDTO from './GroupScoreChunkDTO';

/**
 * The SearchOverGroupsResponseBody model module.
 * @module model/SearchOverGroupsResponseBody
 * @version 0.5.0
 */
class SearchOverGroupsResponseBody {
    /**
     * Constructs a new <code>SearchOverGroupsResponseBody</code>.
     * @alias module:model/SearchOverGroupsResponseBody
     * @param groupChunks {Array.<module:model/GroupScoreChunkDTO>} 
     * @param totalChunkPages {Number} 
     */
    constructor(groupChunks, totalChunkPages) { 
        
        SearchOverGroupsResponseBody.initialize(this, groupChunks, totalChunkPages);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, groupChunks, totalChunkPages) { 
        obj['group_chunks'] = groupChunks;
        obj['total_chunk_pages'] = totalChunkPages;
    }

    /**
     * Constructs a <code>SearchOverGroupsResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchOverGroupsResponseBody} obj Optional instance to populate.
     * @return {module:model/SearchOverGroupsResponseBody} The populated <code>SearchOverGroupsResponseBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchOverGroupsResponseBody();

            if (data.hasOwnProperty('group_chunks')) {
                obj['group_chunks'] = ApiClient.convertToType(data['group_chunks'], [GroupScoreChunkDTO]);
            }
            if (data.hasOwnProperty('total_chunk_pages')) {
                obj['total_chunk_pages'] = ApiClient.convertToType(data['total_chunk_pages'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchOverGroupsResponseBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchOverGroupsResponseBody</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SearchOverGroupsResponseBody.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['group_chunks']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['group_chunks'])) {
                throw new Error("Expected the field `group_chunks` to be an array in the JSON data but got " + data['group_chunks']);
            }
            // validate the optional field `group_chunks` (array)
            for (const item of data['group_chunks']) {
                GroupScoreChunkDTO.validateJSON(item);
            };
        }

        return true;
    }


}

SearchOverGroupsResponseBody.RequiredProperties = ["group_chunks", "total_chunk_pages"];

/**
 * @member {Array.<module:model/GroupScoreChunkDTO>} group_chunks
 */
SearchOverGroupsResponseBody.prototype['group_chunks'] = undefined;

/**
 * @member {Number} total_chunk_pages
 */
SearchOverGroupsResponseBody.prototype['total_chunk_pages'] = undefined;






export default SearchOverGroupsResponseBody;

