/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SetUserApiKeyResponse model module.
 * @module model/SetUserApiKeyResponse
 * @version 0.5.0
 */
class SetUserApiKeyResponse {
    /**
     * Constructs a new <code>SetUserApiKeyResponse</code>.
     * @alias module:model/SetUserApiKeyResponse
     * @param apiKey {String} The api key which was created. This is the value which should be used in the Authorization header.
     */
    constructor(apiKey) { 
        
        SetUserApiKeyResponse.initialize(this, apiKey);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, apiKey) { 
        obj['api_key'] = apiKey;
    }

    /**
     * Constructs a <code>SetUserApiKeyResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetUserApiKeyResponse} obj Optional instance to populate.
     * @return {module:model/SetUserApiKeyResponse} The populated <code>SetUserApiKeyResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetUserApiKeyResponse();

            if (data.hasOwnProperty('api_key')) {
                obj['api_key'] = ApiClient.convertToType(data['api_key'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SetUserApiKeyResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SetUserApiKeyResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SetUserApiKeyResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['api_key'] && !(typeof data['api_key'] === 'string' || data['api_key'] instanceof String)) {
            throw new Error("Expected the field `api_key` to be a primitive type in the JSON string but got " + data['api_key']);
        }

        return true;
    }


}

SetUserApiKeyResponse.RequiredProperties = ["api_key"];

/**
 * The api key which was created. This is the value which should be used in the Authorization header.
 * @member {String} api_key
 */
SetUserApiKeyResponse.prototype['api_key'] = undefined;






export default SetUserApiKeyResponse;

