/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SlimGroup model module.
 * @module model/SlimGroup
 * @version 0.5.0
 */
class SlimGroup {
    /**
     * Constructs a new <code>SlimGroup</code>.
     * @alias module:model/SlimGroup
     * @param datasetId {String} 
     * @param id {String} 
     * @param name {String} 
     * @param ofCurrentDataset {Boolean} 
     */
    constructor(datasetId, id, name, ofCurrentDataset) { 
        
        SlimGroup.initialize(this, datasetId, id, name, ofCurrentDataset);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, datasetId, id, name, ofCurrentDataset) { 
        obj['dataset_id'] = datasetId;
        obj['id'] = id;
        obj['name'] = name;
        obj['of_current_dataset'] = ofCurrentDataset;
    }

    /**
     * Constructs a <code>SlimGroup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SlimGroup} obj Optional instance to populate.
     * @return {module:model/SlimGroup} The populated <code>SlimGroup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SlimGroup();

            if (data.hasOwnProperty('dataset_id')) {
                obj['dataset_id'] = ApiClient.convertToType(data['dataset_id'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('of_current_dataset')) {
                obj['of_current_dataset'] = ApiClient.convertToType(data['of_current_dataset'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SlimGroup</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SlimGroup</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SlimGroup.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['dataset_id'] && !(typeof data['dataset_id'] === 'string' || data['dataset_id'] instanceof String)) {
            throw new Error("Expected the field `dataset_id` to be a primitive type in the JSON string but got " + data['dataset_id']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

SlimGroup.RequiredProperties = ["dataset_id", "id", "name", "of_current_dataset"];

/**
 * @member {String} dataset_id
 */
SlimGroup.prototype['dataset_id'] = undefined;

/**
 * @member {String} id
 */
SlimGroup.prototype['id'] = undefined;

/**
 * @member {String} name
 */
SlimGroup.prototype['name'] = undefined;

/**
 * @member {Boolean} of_current_dataset
 */
SlimGroup.prototype['of_current_dataset'] = undefined;






export default SlimGroup;

