/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Topic model module.
 * @module model/Topic
 * @version 0.5.0
 */
class Topic {
    /**
     * Constructs a new <code>Topic</code>.
     * @alias module:model/Topic
     * @param createdAt {Date} 
     * @param datasetId {String} 
     * @param deleted {Boolean} 
     * @param id {String} 
     * @param name {String} 
     * @param updatedAt {Date} 
     * @param userId {String} 
     */
    constructor(createdAt, datasetId, deleted, id, name, updatedAt, userId) { 
        
        Topic.initialize(this, createdAt, datasetId, deleted, id, name, updatedAt, userId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, createdAt, datasetId, deleted, id, name, updatedAt, userId) { 
        obj['created_at'] = createdAt;
        obj['dataset_id'] = datasetId;
        obj['deleted'] = deleted;
        obj['id'] = id;
        obj['name'] = name;
        obj['updated_at'] = updatedAt;
        obj['user_id'] = userId;
    }

    /**
     * Constructs a <code>Topic</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Topic} obj Optional instance to populate.
     * @return {module:model/Topic} The populated <code>Topic</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Topic();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('dataset_id')) {
                obj['dataset_id'] = ApiClient.convertToType(data['dataset_id'], 'String');
            }
            if (data.hasOwnProperty('deleted')) {
                obj['deleted'] = ApiClient.convertToType(data['deleted'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Topic</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Topic</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Topic.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['dataset_id'] && !(typeof data['dataset_id'] === 'string' || data['dataset_id'] instanceof String)) {
            throw new Error("Expected the field `dataset_id` to be a primitive type in the JSON string but got " + data['dataset_id']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }

        return true;
    }


}

Topic.RequiredProperties = ["created_at", "dataset_id", "deleted", "id", "name", "updated_at", "user_id"];

/**
 * @member {Date} created_at
 */
Topic.prototype['created_at'] = undefined;

/**
 * @member {String} dataset_id
 */
Topic.prototype['dataset_id'] = undefined;

/**
 * @member {Boolean} deleted
 */
Topic.prototype['deleted'] = undefined;

/**
 * @member {String} id
 */
Topic.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Topic.prototype['name'] = undefined;

/**
 * @member {Date} updated_at
 */
Topic.prototype['updated_at'] = undefined;

/**
 * @member {String} user_id
 */
Topic.prototype['user_id'] = undefined;






export default Topic;

