/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateDatasetRequest model module.
 * @module model/UpdateDatasetRequest
 * @version 0.5.0
 */
class UpdateDatasetRequest {
    /**
     * Constructs a new <code>UpdateDatasetRequest</code>.
     * @alias module:model/UpdateDatasetRequest
     * @param datasetId {String} The id of the dataset you want to update.
     */
    constructor(datasetId) { 
        
        UpdateDatasetRequest.initialize(this, datasetId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, datasetId) { 
        obj['dataset_id'] = datasetId;
    }

    /**
     * Constructs a <code>UpdateDatasetRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateDatasetRequest} obj Optional instance to populate.
     * @return {module:model/UpdateDatasetRequest} The populated <code>UpdateDatasetRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateDatasetRequest();

            if (data.hasOwnProperty('client_configuration')) {
                obj['client_configuration'] = ApiClient.convertToType(data['client_configuration'], Object);
            }
            if (data.hasOwnProperty('dataset_id')) {
                obj['dataset_id'] = ApiClient.convertToType(data['dataset_id'], 'String');
            }
            if (data.hasOwnProperty('dataset_name')) {
                obj['dataset_name'] = ApiClient.convertToType(data['dataset_name'], 'String');
            }
            if (data.hasOwnProperty('server_configuration')) {
                obj['server_configuration'] = ApiClient.convertToType(data['server_configuration'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateDatasetRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateDatasetRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateDatasetRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['dataset_id'] && !(typeof data['dataset_id'] === 'string' || data['dataset_id'] instanceof String)) {
            throw new Error("Expected the field `dataset_id` to be a primitive type in the JSON string but got " + data['dataset_id']);
        }
        // ensure the json data is a string
        if (data['dataset_name'] && !(typeof data['dataset_name'] === 'string' || data['dataset_name'] instanceof String)) {
            throw new Error("Expected the field `dataset_name` to be a primitive type in the JSON string but got " + data['dataset_name']);
        }

        return true;
    }


}

UpdateDatasetRequest.RequiredProperties = ["dataset_id"];

/**
 * The new client configuration of the dataset, can be arbitrary JSON. See docs.trieve.ai for more information. If not provided, the client configuration will not be updated.
 * @member {Object} client_configuration
 */
UpdateDatasetRequest.prototype['client_configuration'] = undefined;

/**
 * The id of the dataset you want to update.
 * @member {String} dataset_id
 */
UpdateDatasetRequest.prototype['dataset_id'] = undefined;

/**
 * The new name of the dataset. Must be unique within the organization. If not provided, the name will not be updated.
 * @member {String} dataset_name
 */
UpdateDatasetRequest.prototype['dataset_name'] = undefined;

/**
 * The new server configuration of the dataset, can be arbitrary JSON. See docs.trieve.ai for more information. If not provided, the server configuration will not be updated.
 * @member {Object} server_configuration
 */
UpdateDatasetRequest.prototype['server_configuration'] = undefined;






export default UpdateDatasetRequest;

