/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrieveJsTsClient);
  }
}(this, function(expect, TrieveJsTsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrieveJsTsClient.ClientDatasetConfiguration();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ClientDatasetConfiguration', function() {
    it('should create an instance of ClientDatasetConfiguration', function() {
      // uncomment below and update the code to test ClientDatasetConfiguration
      //var instance = new TrieveJsTsClient.ClientDatasetConfiguration();
      //expect(instance).to.be.a(TrieveJsTsClient.ClientDatasetConfiguration);
    });

    it('should have the property CREATE_CHUNK_FEATURE (base name: "CREATE_CHUNK_FEATURE")', function() {
      // uncomment below and update the code to test the property CREATE_CHUNK_FEATURE
      //var instance = new TrieveJsTsClient.ClientDatasetConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property DATE_RANGE_VALUE (base name: "DATE_RANGE_VALUE")', function() {
      // uncomment below and update the code to test the property DATE_RANGE_VALUE
      //var instance = new TrieveJsTsClient.ClientDatasetConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property DOCUMENT_UPLOAD_FEATURE (base name: "DOCUMENT_UPLOAD_FEATURE")', function() {
      // uncomment below and update the code to test the property DOCUMENT_UPLOAD_FEATURE
      //var instance = new TrieveJsTsClient.ClientDatasetConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property FILE_NAME_KEY (base name: "FILE_NAME_KEY")', function() {
      // uncomment below and update the code to test the property FILE_NAME_KEY
      //var instance = new TrieveJsTsClient.ClientDatasetConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property FILTER_ITEMS (base name: "FILTER_ITEMS")', function() {
      // uncomment below and update the code to test the property FILTER_ITEMS
      //var instance = new TrieveJsTsClient.ClientDatasetConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property FRONTMATTER_VALS (base name: "FRONTMATTER_VALS")', function() {
      // uncomment below and update the code to test the property FRONTMATTER_VALS
      //var instance = new TrieveJsTsClient.ClientDatasetConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property IMAGE_RANGE_END_KEY (base name: "IMAGE_RANGE_END_KEY")', function() {
      // uncomment below and update the code to test the property IMAGE_RANGE_END_KEY
      //var instance = new TrieveJsTsClient.ClientDatasetConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property IMAGE_RANGE_START_KEY (base name: "IMAGE_RANGE_START_KEY")', function() {
      // uncomment below and update the code to test the property IMAGE_RANGE_START_KEY
      //var instance = new TrieveJsTsClient.ClientDatasetConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property LINES_BEFORE_SHOW_MORE (base name: "LINES_BEFORE_SHOW_MORE")', function() {
      // uncomment below and update the code to test the property LINES_BEFORE_SHOW_MORE
      //var instance = new TrieveJsTsClient.ClientDatasetConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property SEARCH_QUERIES (base name: "SEARCH_QUERIES")', function() {
      // uncomment below and update the code to test the property SEARCH_QUERIES
      //var instance = new TrieveJsTsClient.ClientDatasetConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property SUGGESTED_QUERIES (base name: "SUGGESTED_QUERIES")', function() {
      // uncomment below and update the code to test the property SUGGESTED_QUERIES
      //var instance = new TrieveJsTsClient.ClientDatasetConfiguration();
      //expect(instance).to.be();
    });

  });

}));
