/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrieveJsTsClient);
  }
}(this, function(expect, TrieveJsTsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrieveJsTsClient.SearchChunkQueryResponseBody();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SearchChunkQueryResponseBody', function() {
    it('should create an instance of SearchChunkQueryResponseBody', function() {
      // uncomment below and update the code to test SearchChunkQueryResponseBody
      //var instance = new TrieveJsTsClient.SearchChunkQueryResponseBody();
      //expect(instance).to.be.a(TrieveJsTsClient.SearchChunkQueryResponseBody);
    });

    it('should have the property scoreChunks (base name: "score_chunks")', function() {
      // uncomment below and update the code to test the property scoreChunks
      //var instance = new TrieveJsTsClient.SearchChunkQueryResponseBody();
      //expect(instance).to.be();
    });

    it('should have the property totalChunkPages (base name: "total_chunk_pages")', function() {
      // uncomment below and update the code to test the property totalChunkPages
      //var instance = new TrieveJsTsClient.SearchChunkQueryResponseBody();
      //expect(instance).to.be();
    });

  });

}));
