/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrieveJsTsClient);
  }
}(this, function(expect, TrieveJsTsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrieveJsTsClient.SlimUser();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SlimUser', function() {
    it('should create an instance of SlimUser', function() {
      // uncomment below and update the code to test SlimUser
      //var instance = new TrieveJsTsClient.SlimUser();
      //expect(instance).to.be.a(TrieveJsTsClient.SlimUser);
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new TrieveJsTsClient.SlimUser();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TrieveJsTsClient.SlimUser();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new TrieveJsTsClient.SlimUser();
      //expect(instance).to.be();
    });

    it('should have the property orgs (base name: "orgs")', function() {
      // uncomment below and update the code to test the property orgs
      //var instance = new TrieveJsTsClient.SlimUser();
      //expect(instance).to.be();
    });

    it('should have the property userOrgs (base name: "user_orgs")', function() {
      // uncomment below and update the code to test the property userOrgs
      //var instance = new TrieveJsTsClient.SlimUser();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new TrieveJsTsClient.SlimUser();
      //expect(instance).to.be();
    });

    it('should have the property visibleEmail (base name: "visible_email")', function() {
      // uncomment below and update the code to test the property visibleEmail
      //var instance = new TrieveJsTsClient.SlimUser();
      //expect(instance).to.be();
    });

    it('should have the property website (base name: "website")', function() {
      // uncomment below and update the code to test the property website
      //var instance = new TrieveJsTsClient.SlimUser();
      //expect(instance).to.be();
    });

  });

}));
