/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrieveJsTsClient);
  }
}(this, function(expect, TrieveJsTsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrieveJsTsClient.StripePlan();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StripePlan', function() {
    it('should create an instance of StripePlan', function() {
      // uncomment below and update the code to test StripePlan
      //var instance = new TrieveJsTsClient.StripePlan();
      //expect(instance).to.be.a(TrieveJsTsClient.StripePlan);
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new TrieveJsTsClient.StripePlan();
      //expect(instance).to.be();
    });

    it('should have the property chunkCount (base name: "chunk_count")', function() {
      // uncomment below and update the code to test the property chunkCount
      //var instance = new TrieveJsTsClient.StripePlan();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new TrieveJsTsClient.StripePlan();
      //expect(instance).to.be();
    });

    it('should have the property datasetCount (base name: "dataset_count")', function() {
      // uncomment below and update the code to test the property datasetCount
      //var instance = new TrieveJsTsClient.StripePlan();
      //expect(instance).to.be();
    });

    it('should have the property fileStorage (base name: "file_storage")', function() {
      // uncomment below and update the code to test the property fileStorage
      //var instance = new TrieveJsTsClient.StripePlan();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TrieveJsTsClient.StripePlan();
      //expect(instance).to.be();
    });

    it('should have the property messageCount (base name: "message_count")', function() {
      // uncomment below and update the code to test the property messageCount
      //var instance = new TrieveJsTsClient.StripePlan();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new TrieveJsTsClient.StripePlan();
      //expect(instance).to.be();
    });

    it('should have the property stripeId (base name: "stripe_id")', function() {
      // uncomment below and update the code to test the property stripeId
      //var instance = new TrieveJsTsClient.StripePlan();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new TrieveJsTsClient.StripePlan();
      //expect(instance).to.be();
    });

    it('should have the property userCount (base name: "user_count")', function() {
      // uncomment below and update the code to test the property userCount
      //var instance = new TrieveJsTsClient.StripePlan();
      //expect(instance).to.be();
    });

  });

}));
