/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrieveJsTsClient);
  }
}(this, function(expect, TrieveJsTsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrieveJsTsClient.UpdateChunkByTrackingIdData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateChunkByTrackingIdData', function() {
    it('should create an instance of UpdateChunkByTrackingIdData', function() {
      // uncomment below and update the code to test UpdateChunkByTrackingIdData
      //var instance = new TrieveJsTsClient.UpdateChunkByTrackingIdData();
      //expect(instance).to.be.a(TrieveJsTsClient.UpdateChunkByTrackingIdData);
    });

    it('should have the property chunkHtml (base name: "chunk_html")', function() {
      // uncomment below and update the code to test the property chunkHtml
      //var instance = new TrieveJsTsClient.UpdateChunkByTrackingIdData();
      //expect(instance).to.be();
    });

    it('should have the property groupIds (base name: "group_ids")', function() {
      // uncomment below and update the code to test the property groupIds
      //var instance = new TrieveJsTsClient.UpdateChunkByTrackingIdData();
      //expect(instance).to.be();
    });

    it('should have the property groupTrackingIds (base name: "group_tracking_ids")', function() {
      // uncomment below and update the code to test the property groupTrackingIds
      //var instance = new TrieveJsTsClient.UpdateChunkByTrackingIdData();
      //expect(instance).to.be();
    });

    it('should have the property link (base name: "link")', function() {
      // uncomment below and update the code to test the property link
      //var instance = new TrieveJsTsClient.UpdateChunkByTrackingIdData();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new TrieveJsTsClient.UpdateChunkByTrackingIdData();
      //expect(instance).to.be();
    });

    it('should have the property timeStamp (base name: "time_stamp")', function() {
      // uncomment below and update the code to test the property timeStamp
      //var instance = new TrieveJsTsClient.UpdateChunkByTrackingIdData();
      //expect(instance).to.be();
    });

    it('should have the property trackingId (base name: "tracking_id")', function() {
      // uncomment below and update the code to test the property trackingId
      //var instance = new TrieveJsTsClient.UpdateChunkByTrackingIdData();
      //expect(instance).to.be();
    });

    it('should have the property weight (base name: "weight")', function() {
      // uncomment below and update the code to test the property weight
      //var instance = new TrieveJsTsClient.UpdateChunkByTrackingIdData();
      //expect(instance).to.be();
    });

  });

}));
