/**
 * Trieve API
 * Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: developers@trieve.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrieveJsTsClient);
  }
}(this, function(expect, TrieveJsTsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrieveJsTsClient.ChunkApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChunkApi', function() {
    describe('createChunk', function() {
      it('should call createChunk successfully', function(done) {
        //uncomment below and update the code to test createChunk
        //instance.createChunk(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createSuggestedQueriesHandler', function() {
      it('should call createSuggestedQueriesHandler successfully', function(done) {
        //uncomment below and update the code to test createSuggestedQueriesHandler
        //instance.createSuggestedQueriesHandler(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteChunk', function() {
      it('should call deleteChunk successfully', function(done) {
        //uncomment below and update the code to test deleteChunk
        //instance.deleteChunk(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteChunkByTrackingId', function() {
      it('should call deleteChunkByTrackingId successfully', function(done) {
        //uncomment below and update the code to test deleteChunkByTrackingId
        //instance.deleteChunkByTrackingId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('generateOffChunks', function() {
      it('should call generateOffChunks successfully', function(done) {
        //uncomment below and update the code to test generateOffChunks
        //instance.generateOffChunks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getChunkById', function() {
      it('should call getChunkById successfully', function(done) {
        //uncomment below and update the code to test getChunkById
        //instance.getChunkById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getChunkByTrackingId', function() {
      it('should call getChunkByTrackingId successfully', function(done) {
        //uncomment below and update the code to test getChunkByTrackingId
        //instance.getChunkByTrackingId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRecommendedChunks', function() {
      it('should call getRecommendedChunks successfully', function(done) {
        //uncomment below and update the code to test getRecommendedChunks
        //instance.getRecommendedChunks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchChunk', function() {
      it('should call searchChunk successfully', function(done) {
        //uncomment below and update the code to test searchChunk
        //instance.searchChunk(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateChunk', function() {
      it('should call updateChunk successfully', function(done) {
        //uncomment below and update the code to test updateChunk
        //instance.updateChunk(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateChunkByTrackingId', function() {
      it('should call updateChunkByTrackingId successfully', function(done) {
        //uncomment below and update the code to test updateChunkByTrackingId
        //instance.updateChunkByTrackingId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
